# Generated by Django 6.0.3 on 2026-04-02 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_slug_product_slug_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
